[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "cosmodyn"
version = "0.1.0"
description = "A semi-analytic framework for the dynamical evolution of compact stellar systems in cosmological simulations."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
    { name = "Pierre Boldrini" }
]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "astropy",
    "h5py",
    "galpy",
    "tqdm",
    "pandas",
]


[tool.setuptools]
package-dir = { "" = "src" }
packages = [
    "cosmodyn",
    "cosmodyn.initial_conditions",
    "cosmodyn.dynamics",
]